Repository THT-Team/THT-Android, pull requests merged in 2022-12, with the labels that each got.

#2 Architect `:domain` `:data` module
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/tht/tht/TopicHotTodayApp.kt
  build.gradle
  data/.gitignore
  data/build.gradle
  data/src/main/java/com/tht/tht/data/MyClass.kt
  domain/.gitignore
  domain/build.gradle
  domain/src/main/java/com/tht/tht/domain/MyClass.kt
  settings.gradle
Labels: 남태우 🕷, chore 📏

#4 Move pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 남태우 🕷, chore 📏

#7 chore: #5,#6 - create android continuous integration
  .editorconfig
  app/build.gradle
  app/src/androidTest/java/com/tht/tht/ExampleInstrumentedTest.kt
  app/src/main/java/com/tht/tht/MainActivity.kt
  app/src/main/java/com/tht/tht/TopicHotTodayApp.kt
  app/src/test/java/com/tht/tht/ExampleUnitTest.kt
  build.gradle
  detekt-config.yml
  detekt.gradle
Labels: 남태우 🕷, chore 📏

#9 chore: #8 - android_ci 추가 설정
  .github/workflows/android.yml
  .github/workflows/android_ci.yml
Labels: 최웅재 🦊, chore 📏

#12 chore: #10 - Version Catalog 설정
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  data/build.gradle.kts
  detekt.gradle.kts
  domain/build.gradle.kts
  gradle/libraries.version.toml
  settings.gradle.kts
Labels: chore 📏
