Repository THT-Team/THT-Android, pull requests merged in 2023-01, with the labels that each got.

#16 TOP-2 feat: add color resource
  app/src/main/res/values/colors.xml
Labels: 최웅재 🦊, ui 🖍

#15 chore: #14 - hilt 의존성 라이브러리 추가
  app/build.gradle.kts
  app/src/main/java/com/tht/tht/MainActivity.kt
  app/src/main/java/com/tht/tht/TopicHotTodayApp.kt
  build.gradle.kts
  gradle/libraries.version.toml
Labels: 남태우 🕷, chore 📏

#18 TOP-7 feat: mockk 테스트 의존성 추가
  app/build.gradle.kts
  gradle/libraries.version.toml
Labels: 최웅재 🦊, feat 📎

#19 TOP-7 feat: Data, Domain 모듈에 mockk 테스트 의존성 추가
  data/build.gradle.kts
  domain/build.gradle.kts
Labels: 최웅재 🦊, feat 📎

#17 TOP-1 feat: 데이터 레이어 구조 설계
  data/src/main/java/com/tht/tht/data/datasource/Datasource.kt
  data/src/main/java/com/tht/tht/data/remote/datasource/Datasource.kt
  data/src/main/java/com/tht/tht/data/remote/mapper/Mapper.kt
  data/src/main/java/com/tht/tht/data/remote/request/request.kt
  data/src/main/java/com/tht/tht/data/remote/response/BaseResponse.kt
  data/src/main/java/com/tht/tht/data/remote/response/ErrorResponse.kt
  data/src/main/java/com/tht/tht/data/remote/response/SuccessResponse.kt
  data/src/main/java/com/tht/tht/data/remote/retrofit/retrofit.kt
  data/src/main/java/com/tht/tht/data/remote/service/service.kt
  data/src/main/java/com/tht/tht/data/repository/RepositoryImpl.kt
Labels: 남태우 🕷, feat 📎

#20 TOP-6 feat: 네트워크 연결작업
  data/build.gradle.kts
  data/src/main/java/com/tht/tht/data/di/retrofit/ApiModule.kt
  data/src/main/java/com/tht/tht/data/di/retrofit/GsonModule.kt
  data/src/main/java/com/tht/tht/data/di/retrofit/OkHttpClientModule.kt
  data/src/main/java/com/tht/tht/data/di/retrofit/OkHttpInterceptorModule.kt
  data/src/main/java/com/tht/tht/data/remote/response/BaseResponse.kt
  data/src/main/java/com/tht/tht/data/remote/retrofit/ApiClient.kt
  data/src/main/java/com/tht/tht/data/remote/retrofit/callAdapter/ApiCall.kt
  data/src/main/java/com/tht/tht/data/remote/retrofit/callAdapter/ApiCallAdapter.kt
  data/src/main/java/com/tht/tht/data/remote/retrofit/callAdapter/ApiCallAdapterFactory.kt
  data/src/main/java/com/tht/tht/data/remote/retrofit/header/HttpHeaderKey.kt
  data/src/main/java/com/tht/tht/data/remote/service/service.kt
  gradle/libraries.version.toml
Labels: 남태우 🕷, feat 📎

#21 TOP-5 feat: 회원가입 Domain 코드, 테스트 케이스 작성
  data/build.gradle.kts
  domain/build.gradle.kts
  domain/src/main/java/com/tht/tht/domain/MyClass.kt
  domain/src/main/java/com/tht/tht/domain/signup/constant/SignupConstant.kt
  domain/src/main/java/com/tht/tht/domain/signup/model/IdealTypeModel.kt
  domain/src/main/java/com/tht/tht/domain/signup/model/InterestModel.kt
  domain/src/main/java/com/tht/tht/domain/signup/model/SignupException.kt
  domain/src/main/java/com/tht/tht/domain/signup/model/SignupUserModel.kt
  domain/src/main/java/com/tht/tht/domain/signup/model/TermsModel.kt
  domain/src/main/java/com/tht/tht/domain/signup/repository/SignupRepository.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/CreateSignupUserUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/FetchIdealTypeUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/FetchInterestUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/FetchSignupUserUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/FetchTermsUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupBirtheUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupEmailUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupGenderUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupIdealTypeUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupInterestUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupIntroduceUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupLocationUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupNickNameUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupPreferredGenderUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupProfileImagesUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchSignupTermsUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/RemoveSignupUserUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/RequestAuthenticationUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/RequestSignupUseCase.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/RequestVerifyUseCase.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/CreateSignupUserUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/FetchIdealTypeUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/FetchInterestUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/FetchSignupUserUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/FetchTermsUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupBirtheUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupEmailUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupGenderUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupIdealTypeUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupInterestUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupIntroduceUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupLocationUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupNickNameUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupPreferredGenderUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupProfileImagesUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchSignupTermsUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/RemoveSignupUserUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/RequestAuthenticationUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/RequestSignupUseCaseTest.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/RequestVerifyUseCaseTest.kt
  gradle/libraries.version.toml
Labels: 최웅재 🦊, feat 📎, test ✍️
