Repository THT-Team/THT-Android, pull requests merged in 2023-09, with the labels that each got.

#97 TOP-71 feature 일시정지 기능 변경
  core/compose-ui/src/main/java/com/example/compose_ui/component/text/headline/Headline.kt
  core/compose-ui/src/main/java/com/example/compose_ui/component/text/p/p.kt
  core/compose-ui/src/main/java/com/example/compose_ui/extensions/ModifierExtension.kt
  feature/tohot/build.gradle.kts
  feature/tohot/src/main/java/tht/feature/tohot/component/card/ToHotCard.kt
  feature/tohot/src/main/java/tht/feature/tohot/component/card/ToHotHoldCard.kt
  feature/tohot/src/main/java/tht/feature/tohot/component/hold/BlurContent.kt
  feature/tohot/src/main/java/tht/feature/tohot/component/hold/ToHotHoldUi.kt
  feature/tohot/src/main/java/tht/feature/tohot/component/pager/ToHotCardImagePager.kt
  feature/tohot/src/main/java/tht/feature/tohot/component/progress/ToHotAnimateTimeProgressContainer.kt
  feature/tohot/src/main/java/tht/feature/tohot/component/toolbar/ToHotToolBarContent.kt
  feature/tohot/src/main/java/tht/feature/tohot/model/CardTimerUiModel.kt
  feature/tohot/src/main/java/tht/feature/tohot/tohot/route/ToHotRoute.kt
  feature/tohot/src/main/java/tht/feature/tohot/tohot/screen/ToHotScreen.kt
  feature/tohot/src/main/java/tht/feature/tohot/tohot/state/ToHotState.kt
  feature/tohot/src/main/java/tht/feature/tohot/tohot/viewmodel/ToHotViewModel.kt
  feature/tohot/src/main/res/drawable-hdpi/ic_topic_default.png
  feature/tohot/src/main/res/drawable-mdpi/ic_topic_default.png
  feature/tohot/src/main/res/drawable-xhdpi/ic_topic_default.png
  feature/tohot/src/main/res/drawable-xxhdpi/ic_topic_default.png
  feature/tohot/src/main/res/drawable-xxxhdpi/ic_topic_default.png
  feature/tohot/src/main/res/drawable/ic_pause.xml
  feature/tohot/src/main/res/values/strings.xml
  gradle/libraries.version.toml
  settings.gradle.kts
Labels: 최웅재 🦊, feat 📎

#98 TOP-76 modify 닉네임 중복 체크 기능 비활성화
  feature/signin/src/main/java/tht/feature/signin/signup/nickname/NicknameViewModel.kt
Labels: 최웅재 🦊, modify ⌨️

#105 TOP-83 Fix patch location fail
  domain/src/main/java/com/tht/tht/domain/signup/model/SignupException.kt
  domain/src/main/java/com/tht/tht/domain/signup/usecase/PatchLocationUseCase.kt
  domain/src/test/java/com/tht/tht/domain/signup/usecase/PatchLocationUseCaseImpl.kt
  feature/signin/src/main/java/tht/feature/signin/StringProvider.kt
  feature/signin/src/main/java/tht/feature/signin/StringProviderImpl.kt
  feature/signin/src/main/java/tht/feature/signin/signup/location/LocationViewModel.kt
  feature/signin/src/main/res/values/strings.xml
Labels: 최웅재 🦊, fix 🔎

#107 TOP-83 Fix Region Code API Key값이 CI, CD에서 잘못 불러오는 문제
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
Labels: 최웅재 🦊, fix 🔎

#103 TOP-72 Feature tohot card time shaking animation
  feature/tohot/src/main/java/tht/feature/tohot/component/card/ShakingCard.kt
  feature/tohot/src/main/java/tht/feature/tohot/component/card/ToHotCard.kt
  feature/tohot/src/main/java/tht/feature/tohot/component/pager/ToHotCardImagePager.kt
  feature/tohot/src/main/java/tht/feature/tohot/tohot/route/ToHotRoute.kt
  feature/tohot/src/main/java/tht/feature/tohot/tohot/screen/ToHotScreen.kt
  feature/tohot/src/main/java/tht/feature/tohot/tohot/state/ToHotState.kt
  feature/tohot/src/main/java/tht/feature/tohot/tohot/viewmodel/ToHotViewModel.kt
Labels: 최웅재 🦊, feat 📎

#108 Top-85 fix LocationDialog
  feature/signin/src/main/java/tht/feature/signin/signup/location/LocationFragment.kt
Labels: 최광현 🐱, fix 🔎

#104 TOP-69 design PhoneAuth Custom Toast에 이미지 대신 Lottie 애니메이션 적용
  feature/signin/src/main/java/tht/feature/signin/auth/PhoneAuthActivity.kt
  feature/signin/src/main/res/layout/item_signup_custom_toast.xml
  feature/signin/src/main/res/raw/phone_auth_success.json
Labels: 최웅재 🦊, ui 🖍
